apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-ks-app-arm64.fullname" . }}
  # namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "go-ks-app-arm64.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "go-ks-app-arm64.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "go-ks-app-arm64.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresqlSecret.name }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresqlSecret.name }}
                  key: password
            - name: DB_HOST
              value: "{{ .Values.postgresql.name }}-rw"
            - name: DB_PORT
              value: "{{ .Values.postgresql.port }}"
            - name: DB_NAME
              value: "{{ .Values.postgresql.database }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}