apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "my-postgresql.fullname" . }}
  # namespace: {{ .Values.namespace }}
spec:
  instances: {{ .Values.postgresql.instances }}
  storage:
    size: {{ .Values.postgresql.storageSize }}
  bootstrap:
    initdb:
      database: {{ .Values.postgresql.database }}
      owner: {{ .Values.postgresql.owner }}
      secret:
        name: {{ .Values.postgresql.secretName }}