apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
data:
  password: {{ .Values.secretData.password }}
  username: {{ .Values.secretData.username }}