apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresqlSecret.name }}
type: Opaque
data:
  password: {{ .Values.postgresqlSecret.secretData.password }}
  username: {{ .Values.postgresqlSecret.secretData.username  }}