apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: kubesimplify-go
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      name: http
      port: 8088
      targetPort: 8080
  type: ClusterIP