apiVersion: v1
kind: Service
metadata:
  name: go-ks-app-np-service
  namespace: kubesimplify-go
  labels:
    app: go-ks-app
spec:
  selector:
    app: go-ks-app
  ports:
    - protocol: TCP
      name: http
      port: 8087
      targetPort: 8080
  type: NodePort