apiVersion: v1
kind: Service
metadata:
  name: go-ks-app-lb-service
  namespace: kubesimplify-go
spec:
  selector:
    app: go-ks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
